name: student_locker
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_nav_bar: ^5.0.6
  rflutter_alert: ^2.0.7
  cool_alert: ^2.0.1
  quickalert: ^1.1.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  shared_preferences: ^2.2.3
  modal_progress_hud_nsn: ^0.5.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Amiri
      fonts:
        - asset: fonts/Amiri-Regular.ttf
